#include <iostream>

try 
{
    ////
}
catch (const std::overflow_error& e) 
{
//reakcja 1
}
catch (const std::runtime_error& e)
{
//reakacja 2 
}


return 0;
}
